NBA:
  default-categories:
    - Field Goal %
    - Free Throw %
    - Threes
    - Points
    - Rebounds
    - Assists
    - Steals 
    - Blocks
    - Turnovers
  counting-statistics:
    - Threes
    - Points
    - Rebounds
    - Assists
    - Steals 
    - Blocks
    - Turnovers
    - Def Rebounds
    - Off Rebounds
    - Double Doubles 
    - Field Goals Made
    - Free Throws Made
  ratio-statistics: 
    Field Goal % : 
      made-statistic : Field Goals Made
      volume-statistic : Field Goal Attempts
    Free Throw % : 
      made-statistic : Free Throws Made
      volume-statistic : Free Throw Attempts 
    Three %:
      made-statistic: Threes
      volume-statistic: Three Attempts 
    Assist to TO:
      made-statistic: Assists
      volume-statistic: Turnovers
  negative-statistics: 
    - Turnovers
  other-columns:
    - Position
    - Games Played %
  coefficients:
    Field Goal % : 2.23
    Free Throw % : 2.34
    Threes : 1.21
    Points : 1.59
    Rebounds : 1.03
    Assists : 0.88
    Steals : 4.64
    Blocks : 1.19
    Turnovers : 1.85
    Off Rebounds: 0.97
    Def Rebounds: 1.27
    Three %: 12.79
    Double Doubles : 1.06
    Assist to TO : 2.04
    Field Goals Made : 1.83
    Free Throws Made : 1.09
  current-season-api-renamer: 
    PLAYER_NAME : Player
    PTS : Points
    REB : Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    FG3M : Threes
    TOV : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    GAME_DATE : Game Date
  historical-renamer: 
    PLAYER_NAME : Player
    PTS : Points
    REB : Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    FG3M : Threes
    TO : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    date : Date
  rotowire-renamer: 
    NAME : Player
    PTS : Points
    REB : Rebounds
    OREB: Off Rebounds
    DREB: Def Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    3PM : Threes
    TO : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FT% : Free Throw %
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    FG% : Field Goal %
    3P% : Three % 
    3PA: Three Attempts 
    Pos : Position
  rotowire-position-adjuster:
    C : C
    G : PG,SG
    F : PF,SF
  bbm-renamer:
    Name : Player
    g : Games Played
    games : Games Played
    p/g : Points
    r/g : Rebounds
    dr/g : Def Rebounds
    or/g : Off Rebounds
    a/g : Assists
    s/g : Steals
    3/g : Threes
    b/g : Blocks
    to/g : Turnovers
    fta/g: Free Throw Attempts
    ft% : Free Throw %
    fga/g: Field Goal Attempts
    fg%: Field Goal %
    3% : Three %
    3a/g: Three Attempts
    2d/g : Double Doubles
    Pos : Position
  htb-renamer:
    PLAYER : Player
    GP : Games Played
    PTS : Points
    TREB : Rebounds
    OREB: Off Rebounds
    DREB: Def Rebounds
    AST : Assists
    STL : Steals
    3PM : Threes
    BLK : Blocks
    TO : Turnovers
    FTA : Free Throw Attempts
    FT% : Free Throw %
    FGA : Field Goal Attempts
    FG% : Field Goal %
    3P% : Three %
    3PA : Three Attempts
    DD: Double Doubles
    POS : Position
  stat-df-renamer:
    SEASON : Season
    NBA_PLAYER_NAME : Player
    POINTS : Points
    REBOUNDS : Rebounds
    DEFENSIVE_REBOUNDS : Def Rebounds
    OFFENSIVE_REBOUNDS : Off Rebounds
    ASSISTS : Assists
    STEALS : Steals
    BLOCKS : Blocks
    THREES : Threes
    TURNOVERS : Turnovers
    FREE_THROWS_MADE : Free Throws Made
    FREE_THROW_ATTEMPTS : Free Throw Attempts
    FIELD_GOALS_MADE : Field Goals Made
    FIELD_GOAL_ATTEMPTS : Field Goal Attempts
    THREE_ATTEMPTS : Three Attempts 
    DOUBLE_DOUBLE : Double Doubles
    POSITION_LIST : Position
    GAMES_PLAYED_PERCENT : Games Played %
  darko-renamer:
    NBA_PLAYER_NAME : Player
    POINTS_PER_HUNDRED : Points/100
    REBOUNDS_PER_HUNDRED  : Rebounds/100
    ASSISTS_PER_HUNDRED  : Assists/100
    STEALS_PER_HUNDRED  : Steals/100
    BLOCKS_PER_HUNDRED  : Blocks/100
    THREES_PER_HUNDRED  : Threes/100
    TURNOVERS_PER_HUNDRED  : Turnovers/100
    FREE_THROW_ATTEMPTS_PER_HUNDRED  : Free Throw Attempts/100
    FREE_THROW_PERCENT  : Free Throw %
    FIELD_GOAL_ATTEMPTS_PER_HUNDRED  : Field Goal Attempts/100
    FIELD_GOAL_PERCENT  : Field Goal %
    THREE_ATTEMPTS_PER_HUNDRED : Three Attempts/100
    THREE_PERCENT : Three % 
    PACE : Pace
  schedule-url : https://cdn.nba.com/static/json/staticData/scheduleLeagueV2.json 
  z-score-player-multiplier : 50
  z-score-total-multiplier : 40
  z-score-team-multiplier : 20
  g-score-player-multiplier : 60
  g-score-total-multiplier : 50
  g-score-team-multiplier : 24
  options : 
    upsilon : 
      default : 1
      min : 0.0
      max: 1.0
    psi : 
      default : 0.8
      min : 0.0
      max: 1.0
    n_drafters : 
      default : 12
      min : 2
      max: 
    n_picks : 
      default : 13
      min : 1
      max : 
    omega : 
      default : 1.2
      min : 0.0
      max: 2.0
    gamma :
      default : 0.1
      min : 0.0
      max : 1.0
    chi : 
      default : 0.6
      min : 0.0
      max: 1
    n_iterations : 
      min : 0
      max: 10000
    positions: 
     13:
      base:
        C : 2
        PG : 1
        SG : 1
        PF : 1
        SF : 1
      flex: 
        Util : 3
        G :  2
        F :  2
     14: 
      base:
        C : 2
        PG : 1
        SG : 1
        PF : 1
        SF : 1
      flex: 
        Util : 4
        G :  2
        F :  2
     15: 
      base:
        C : 2
        PG : 1
        SG : 1
        PF : 1
        SF : 1
      flex: 
        Util : 3
        G :  3
        F :  3
     16:
        base :
          C : 3
          PG : 1
          SG : 1
          PF : 1
          SF : 1
        flex :
          Util : 3
          G : 3
          F : 3
  position_structure :
    base_list :
      - C
      - PG
      - SG
      - PF
      - SF
    base:
      C : 
        full_str: Centers
      PG : 
        full_str: Point Guards
      SG : 
        full_str: Shooting Guards
      PF : 
        full_str: Power Forwards
      SF : 
        full_str: Small Forwards
    flex_list :
    - Util 
    - G
    - F
    flex: 
      Util : 
        bases: 
        - C
        - PG
        - SG
        - PF
        - SF
        full_str: Utilities
      G : 
        bases: 
        - PG
        - SG
        full_str: Guards
      F: 
        bases: 
        - PF
        - SF
        full_str: Forwards
  punting_defaults :
    No dynamic optimization :
      omega : 0.0 
      gamma : 0.0
      n_iterations : 0
    Moderate punting : 
      omega : 0.7
      gamma : 0.25
      n_iterations : 30
    Aggressive punting : 
      omega : 1.0
      gamma : 0.4
      n_iterations : 30
  punting_default_index : 
    "Head to Head: Most Categories" : 1
    "Head to Head: Each Category" : 1
    "Rotisserie": 1
  n_games : 82
  n_games_per_week : 3
WNBA:
  default-categories:
    - Field Goal %
    - Free Throw %
    - Threes
    - Points
    - Rebounds
    - Assists
    - Steals 
    - Blocks
    - Turnovers
  counting-statistics:
    - Threes
    - Points
    - Rebounds
    - Assists
    - Steals 
    - Blocks
    - Turnovers
    - Def Rebounds
    - Off Rebounds
    - Double Doubles 
  ratio-statistics: 
    Field Goal % : 
      made-statistic : Field Goals Made
      volume-statistic : Field Goal Attempts
    Free Throw % : 
      made-statistic : Free Throws Made
      volume-statistic : Free Throw Attempts 
    Three %:
      made-statistic: Threes
      volume-statistic: Three Attempts 
  negative-statistics: 
    - Turnovers
  other-columns:
    - Position
    - Games Played %
  coefficients:
    Field Goal % : 2.17
    Free Throw % : 2.30
    Threes : 1.11
    Points : 1.45
    Rebounds : 1.00
    Assists : 0.79
    Steals : 4.35
    Blocks : 1.2
    Turnovers : 1.73
  current-season-api-renamer: 
    PLAYER_NAME : Player
    PTS : Points
    REB : Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    FG3M : Threes
    TOV : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    GAME_DATE : Game Date
  historical-renamer: 
    PLAYER_NAME : Player
    PTS : Points
    REB : Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    FG3M : Threes
    TO : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    date : Date
  rotowire-renamer: 
    NAME : Player
    PTS : Points
    REB : Rebounds
    OREB: Off Rebounds
    DREB: Def Rebounds
    AST : Assists
    STL: Steals
    BLK : Blocks
    3PM : Threes
    TO : Turnovers
    FTA : Free Throw Attempts
    FTM : Free Throws Made
    FT% : Free Throw %
    FGA : Field Goal Attempts
    FGM : Field Goals Made
    FG% : Field Goal %
    3P% : Three % 
    3PA: Three Attempts 
    Pos : Position
  rotowire-position-adjuster:
    C : C
    G : PG,SG
    F : PF,SF
  stat-df-renamer:
    SEASON : Season
    NBA_PLAYER_NAME : Player
    POINTS : Points
    REBOUNDS : Rebounds
    ASSISTS : Assists
    STEALS : Steals
    BLOCKS : Blocks
    THREES : Threes
    TURNOVERS : Turnovers
    FREE_THROWS_MADE : Free Throws Made
    FREE_THROW_ATTEMPTS : Free Throw Attempts
    FIELD_GOALS_MADE : Field Goals Made
    FIELD_GOAL_ATTEMPTS : Field Goal Attempts
    POSITION_LIST : Position
    GAMES_PLAYED_PERCENT : Games Played %
  darko-renamer:
    NBA_PLAYER_NAME : Player
    POINTS : Points
    REBOUNDS : Rebounds
    ASSISTS : Assists
    STEALS : Steals
    BLOCKS : Blocks
    THREES : Threes
    TURNOVERS : Turnovers
    FREE_THROW_ATTEMPTS : Free Throw Attempts
    FREE_THROW_PERCENT : Free Throw %
    FIELD_GOAL_ATTEMPTS : Field Goal Attempts
    FIELD_GOAL_PERCENT : Field Goal %
    POSITION_LIST : Position
    MINUTES_PLAYED : Forecasted Minutes
  schedule-url : https://cdn.nba.com/static/json/staticData/scheduleLeagueV2.json 
  z-score-player-multiplier : 50
  z-score-team-multiplier : 20
  g-score-player-multiplier : 60
  g-score-team-multiplier : 24
  options : 
    upsilon : 
      default : 0.5
      min : 0.0
      max: 1.0
    psi : 
      default : 0.8
      min : 0.0
      max: 1.0
    n_drafters : 
      default : 6
      min : 2
      max: 
    n_picks : 
      default : 9
      min : 1
      max : 
    omega : 
      default : 1.2
      min : 0.0
      max: 2.0
    gamma :
      default : 0.1
      min : 0.0
      max : 1.0
    chi : 
      default : 0.6
      min : 0.0
      max: 1
    n_iterations : 
      default : 30
      min : 10
      max: 10000
    positions: 
     9: 
      base:
        C : 2
        PG : 0
        SG : 0
        PF : 0
        SF : 0
      flex: 
        Util : 3
        G :  2
        F :  2
  position_structure :
    base_list :
      - C
      - PG
      - SG
      - PF
      - SF
    base:
      C : 
        full_str: Centers
      PG : 
        full_str: Point Guards
      SG : 
        full_str: Shooting Guards
      PF : 
        full_str: Power Forwards
      SF : 
        full_str: Small Forwards
    flex_list :
    - Util 
    - G
    - F
    flex: 
      Util : 
        bases: 
        - C
        - PG
        - SG
        - PF
        - SF
        full_str: Utilities
      G : 
        bases: 
        - PG
        - SG
        full_str: Guards
      F: 
        bases: 
        - PF
        - SF
        full_str: Forwards
  punting_defaults :
    No dynamic optimization :
      omega : 0.0 
      gamma : 0.0
      n_iterations : 0
    Moderate punting : 
      omega : 0.7
      gamma : 0.25
      n_iterations : 30
    Aggressive punting : 
      omega : 1.0
      gamma : 0.4
      n_iterations : 30
  punting_default_index : 
    "Head to Head: Most Categories" : 1
    "Head to Head: Each Category" : 1
    "Rotisserie": 1
  n_games : 40
  n_games_per_week : 3
MLB:
  default-categories:
    - Runs
    - Home Runs 
    - RBI 
    - Stolen Bases 
    - Batting Average
    - Wins 
    - Saves
    - Strikeouts 
    - ERA
    - WHIP
  counting-statistics:
    - Runs
    - Home Runs 
    - RBI 
    - Stolen Bases 
    - Wins 
    - Saves
    - Strikeouts 
    - Hits 
    - Doubles
    - Triples
    - Total Bases
    - Losses
    - Quality Starts
    - Holds
    - Saves and Holds
  ratio-statistics:
    Batting Average:
      made-statistic: Hits
      volume-statistic: Effective At Bats 
    Slugging %:
      made-statistic : Total Bases
      volume-statistic : Effective At Bats
    On Base %: 
      made-statistic : Batting WH
      volume-statistic: At Bats 
    ERA:
      made-statistic: Earned Runs
      volume-statistic: Innings Pitched
    WHIP:
      made-statistic: Pitching WH
      volume-statistic: Innings Pitched
    K/9: 
      made-statistic: Strikeouts
      volume-statistic: Innings Pitched
    K/BB:
      made-statistic: Strikeouts
      volume-statistic: Walks Pitched 
  negative-statistics:
    - ERA
    - WHIP
    - Losses
  other-columns:
  - Position
  - Games Played %
  coefficients:
    Runs : 1
    Home Runs : 1
    RBI : 1
    Stolen Bases : 0.5
    Batting Average : 1
    Wins : 1
    Saves : 1
    Strikeouts : 1
    ERA : 1
    WHIP : 1
    K/9 : 1
    Slugging % : 1
    On Base % : 1
    Hits : 1
    Doubles : 1
    Triples : 1
    Total Bases : 1
    Losses : 1
    Quality Starts: 1
    Holds : 1
    Saves and Holds : 1
    K/BB : 1
  batter_stats: 
    - Runs
    - Home Runs
    - RBI
    - Stolen Bases
    - Batting Average
    - Slugging %
    - On Base % 
    - Hits
    - Doubles
    - Triples
    - Total Bases
  pitcher_stats:
    - Wins
    - Saves
    - Strikeouts
    - ERA
    - WHIP
    - Innings Pitched
    - Quality Starts
    - Holds
    - Saves and Holds
    - K/9
    - K/BB
  rotowire-renamer:
    Name: Player
    Pos: Position
    R : Runs
    1B : Singles
    2B : Doubles
    3B : Triples
    BB : Walks
    HR : Home Runs
    RBI : RBI
    SB : Stolen Bases
    H : Hits
    AB: At Bats
    AVG: Batting Average
    SLG : Slugging % 
    OBP : On Base % 
    W: Wins
    SV: Saves
    K.1 : Strikeouts
    QS: Quality Starts
    L : Losses
    SV : Saves
    HLD : Holds
    BB/9 : BB/9
    K/BB : K/BB
    ER: Earned Runs
    ERA : ERA
    WHIP : WHIP
    IP: Innings Pitched
    BB.1 : Walks Pitched
  stat-df-renamer:
    MLB_PLAYER_NAME : Player
    SEASON : Season
    HITS : Hits
    AT_BATS : At Bats
    HOME_RUNS : Home Runs
    RBI : RBI
    STOLEN_BASES : Stolen Bases
    WINS : Wins
    SAVES : Saves
    EARNED_RUNS : Earned Runs
    WALKS_AND_HITS: Walks and Hits
    INNINGS_PITCHED : Innings Pitched
    STRIKEOUTS : Strikouts
    QUALITY_STARTS : Quality Starts
    PITCHING_WALKS_AND_HITS : Pitching WH
    BATTING_WALKS_AND_HITS : Batting WH 
    EFFECTIVE_AT_BATS: Effective At Bats
  htb-renamer: 
    GP : Games Played
    R : Runs
    H : Hits
    HR : Home Runs
    RBI : RBI
    2B : Doubles
    3B : Triples
    TB : Total Bases
    SB : Stolen Bases
    AVG: Batting Average
    SLG : Slugging %
    OBP: On Base %
    AB: At Bats
    EAB: Effective At Bats
    W: Wins
    L: Losses
    QS: Quality Starts
    SV: Saves
    HLD: Holds
    SVHLD : Saves and Holds
    K : Strikeouts
    ERA : ERA
    WHIP : WHIP
    K/9 : K/9
    K/BB : K/BB
    IP: Innings Pitched
    PLAYER : Player
    POS : Position
    TEAM : Team
  z-score-total-multiplier : 40
  z-score-team-multiplier : 20
  g-score-player-multiplier : 60
  g-score-total-multiplier : 50
  g-score-team-multiplier : 24
  rotowire-position-adjuster:
    P : SP,RP 
    C : C
    1B : 1B
    2B : 2B
    SS : SS
    3B : 3B
    OF : OF
    DH : DH
  position_structure :
    base_list :
      - C
      - 1B
      - 2B
      - 3B
      - SS
      - OF
      - DH
      - SP
      - RP
    base:
      C : 
        full_str: Catchers
      1B : 
        full_str: First Basemen
      2B : 
        full_str: Second Basemen
      3B : 
        full_str: Third Basemen
      SS : 
        full_str: Shortstop
      OF : 
        full_str: Outfielder
      SP:
        full_str: Starting Pitcher
      RP: 
        full_str: Relief Pitcher 
      DH:
        full_str: Designated Hitter
    flex_list :
    - CI
    - MI
    - Util 
    - P
    flex: 
      CI: 
         bases:
         - 1B
         - 3B
         full_str: Corner Infielders
      MI:
        bases:
        - 2B
        - SS
        full_str: Middle Infielders
      Util : 
        bases: 
        - C
        - 1B
        - 2B
        - 3B
        - SS
        - OF 
        - DH
        full_str: Utilities
      P : 
        bases: 
        - SP
        - RP
        full_str: Pitchers
  options : 
    upsilon : 
      default : 0.5
      min : 0.0
      max: 1.0
    psi : 
      default : 0.8
      min : 0.0
      max: 1.0
    n_drafters : 
      default : 12
      min : 2
      max: 
    n_picks : 
      default : 25
      min : 1
      max : 
    omega : 
      default : 1.2
      min : 0.0
      max: 2.0
    gamma :
      default : 0.1
      min : 0.0
      max : 1.0
    chi : 
      default : 0.6
      min : 0.0
      max: 1
    n_iterations : 
      default : 30
      min : 10
      max: 10000
    positions: 
     25:
      base:
        C : 2
        1B : 1
        2B : 1
        3B : 1
        SS : 1
        OF: 5
        DH : 0
        SP: 4
        RP: 4
      flex: 
        CI: 1
        MI: 1
        Util: 2
        P: 2
  punting_defaults :
    No dynamic optimization :
      omega : 0.0 
      gamma : 0.0
      n_iterations : 0
    Moderate punting : 
      omega : 0.7
      gamma : 0.25
      n_iterations : 30
    Aggressive punting : 
      omega : 1.0
      gamma : 0.4
      n_iterations : 30
  punting_default_index : 
    "Head to Head: Most Categories" : 1
    "Head to Head: Each Category" : 1
    "Rotisserie": 1
  z-score-player-multiplier : 50
  z-score-team-multiplier : 20
  g-score-player-multiplier : 60
  g-score-team-multiplier : 24
  n_games : 162
  n_games_per_week : 0.143 #this is weekly 
