---
counting-statistics:
  - Threes
  - Points
  - Rebounds
  - Assists
  - Steals 
  - Blocks
  - Turnovers
percentage-statistics:
  - Field Goal %
  - Free Throw %
volume-statistics: 
  - Field Goal Attempts
  - Free Throw Attempts
other-columns:
  - Position
api-renamer: 
 PLAYER_NAME : Player
 PTS : Points
 REB : Rebounds
 AST : Assists
 STL: Steals
 BLK : Blocks
 FG3M : Threes
 TOV : Turnovers
 FTA : Free Throw Attempts
 FTM : Free Throws Made
 FGA : Field Goal Attempts
 FGM : Field Goals Made
 GAME_DATE : Game Date
darko-column-renamer:
 PTS : Points
 REB : Rebounds
 AST : Assists
 STL: Steals
 BLK : Blocks
 FG3M : Threes
 TOV : Turnovers
 FTA : Free Throw Attempts
 FGA : Field Goal Attempts
 FT% : Free Throw %
 FG% : Field Goal %
darko-player-renamer : 
  Xavier Tillman : Xavier Tillman Sr.
  P.J. Washington : P.J. Washington Jr.
  GG Jackson : GG Jackson II
  Nicolas Claxton : Nic Claxton
schedule-url : https://cdn.nba.com/static/json/staticData/scheduleLeagueV2.json 
z-score-player-multiplier : 50
z-score-team-multiplier : 20
g-score-player-multiplier : 60
g-score-team-multiplier : 24
defaults : 
 psi : 0
 nu : 0.77
 n_drafters : 12
 n_picks : 13
 omega : 1.0
 gamma : 0.1
 alpha : 0.01
 beta : 0.25
