---
counting-statistics:
  - Threes
  - Points
  - Rebounds
  - Assists
  - Steals 
  - Blocks
  - Turnovers
percentage-statistics:
  - Field Goal %
  - Free Throw %
volume-statistics: 
  - Field Goal Attempts
  - Free Throw Attempts
other-columns:
  - Position
  - Games Played %
current-season-api-renamer: 
 PLAYER_NAME : Player
 PTS : Points
 REB : Rebounds
 AST : Assists
 STL: Steals
 BLK : Blocks
 FG3M : Threes
 TOV : Turnovers
 FTA : Free Throw Attempts
 FTM : Free Throws Made
 FGA : Field Goal Attempts
 FGM : Field Goals Made
 GAME_DATE : Game Date
historical-renamer: 
 PLAYER_NAME : Player
 PTS : Points
 REB : Rebounds
 AST : Assists
 STL: Steals
 BLK : Blocks
 FG3M : Threes
 TO : Turnovers
 FTA : Free Throw Attempts
 FTM : Free Throws Made
 FGA : Field Goal Attempts
 FGM : Field Goals Made
 date : Date
stat-df-renamer:
 SEASON : Season
 NBA_PLAYER_NAME : Player
 POINTS : Points
 REBOUNDS : Rebounds
 ASSISTS : Assists
 STEALS : Steals
 BLOCKS : Blocks
 THREES : Threes
 TURNOVERS : Turnovers
 FREE_THROWS_MADE : Free Throws Made
 FREE_THROW_ATTEMPTS : Free Throw Attempts
 FIELD_GOALS_MADE : Field Goals Made
 FIELD_GOAL_ATTEMPTS : Field Goal Attempts
 POSITION_LIST : Position
 GAMES_PLAYED_PERCENT : Games Played %
darko-renamer:
 NBA_PLAYER_NAME : Player
 POINTS : Points
 REBOUNDS : Rebounds
 ASSISTS : Assists
 STEALS : Steals
 BLOCKS : Blocks
 THREES : Threes
 TURNOVERS : Turnovers
 FREE_THROW_ATTEMPTS : Free Throw Attempts
 FREE_THROW_PERCENT : Free Throw %
 FIELD_GOAL_ATTEMPTS : Field Goal Attempts
 FIELD_GOAL_PERCENT : Field Goal %
 POSITION_LIST : Position
 MINUTES_PLAYED : Forecasted Minutes
schedule-url : https://cdn.nba.com/static/json/staticData/scheduleLeagueV2.json 
z-score-player-multiplier : 50
z-score-team-multiplier : 20
g-score-player-multiplier : 60
g-score-team-multiplier : 24
options : 
 upsilon : 
  default : 0.5
  min : 0.0
  max: 1.0
 psi : 
  default : 0.8
  min : 0.0
  max: 1.0
 n_drafters : 
  default : 12
  min : 2
  max: 
 n_picks : 
  default : 13
  min : 1
  max : 
 omega : 
  default : 1.2
  min : 0.0
  max: 2.0
 gamma :
  default : 0.1
  min : 0.0
  max : 1.0
 chi : 
  default : 0.6
  min : 0.0
  max: 1
 n_iterations : 
  default : 30
  min : 10
  max: 10000
 positions: 
  base:
   C : 2
   PG : 1
   SG : 1
   PF : 1
   SF : 1
  flex: 
   Util : 3
   G :  2
   F :  2
position_structure :
  base_list :
    - C
    - PG
    - SG
    - PF
    - SF
  base:
    C : 
      full_str: Centers
    PG : 
      full_str: Point Guards
    SG : 
      full_str: Shooting Guards
    PF : 
      full_str: Power Forwards
    SF : 
      full_str: Small Forwards
  flex: 
    Util : 
      bases: 
       - C
       - PG
       - SG
       - PF
       - SF
      full_str: Utilities
    G : 
      bases: 
      - PG
      - SG
      full_str: Guards
    F: 
      bases: 
      - PF
      - SF
      full_str: Forwards
punting_defaults :
  No dynamic optimization :
    omega : 0.0 
    gamma : 0.0
  Moderate punting : 
    omega : 0.7
    gamma : 0.25
  Aggressive punting : 
    omega : 1.0
    gamma : 0.4
punting_default_index : 
  "Head to Head: Most Categories" : 1
  "Head to Head: Each Category" : 1
  "Rotisserie": 1
