---
counting-statistics:
  - Points
  - Rebounds
  - Assists
  - Steals 
  - Blocks
  - Threes
  - Turnovers
percentage-statistics:
  - Free Throw %
  - Field Goal %
volume-statistics: 
  - Free Throw Attempts
  - Field Goal Attempts
z-score-player-multiplier : 50
z-score-team-multiplier : 20
g-score-player-multiplier : 60
g-score-team-multiplier : 24
