"""What the self-play animation says out loud.

This is the only file to edit for narration. Each key is one beat of the scene, and that beat's
animation plays INSIDE its line: rewriting a line retimes its own beat rather than
desynchronising everything after it. A beat whose line is short waits for the animation, and one
whose line is long holds the last frame until the sentence finishes.

The voice is gTTS, so what is written here is what is spoken -- spell out anything a reader would
say differently from how it is written ('sigma', 'twenty-six').
"""

NARRATION = {
    'opening':
        'These are expected category-level win rates for the top players, at first generated by the algorithm assuming that '
        'opposing teams will be entirely balanced. Certain punting profiles consistently seem optimal in this context.',
    'why_self_play':
        'In practice, other managers will also use these punts, disincentivizing the punts through competition: '
        'it hardly makes sense for everyone to punt the same category. The point of the self-play process is to account for '
        'that, and find strategies that work well when others are also strategizing.',
    're_estimation':
        'The players are sorted in overall H-score order. The top twelve players and their associated strategy profiles '
        'will constitute the drafting context, against which strategies will be optimized and evaluated. For example, if much '
        'of the field is punting a specific category, then the algorithm will see that it can win that category often without much '
        'investment. ',
    'early_passes':
        'The self-play process has teams re-calibrate themselves against the rest of the field repeatedly, finding new strategies '
        'based on the current field. Overall H-scores can change too, which changes the order of the players, and therefore the '
        'top twelve and the expected drafting context. Every pass re-solves half of the players at a time. The outlined rows '
        'are the ones being re-solved.',
    'late_passes':
        'Over time, the changes get smaller. That means the field is approaching an equilibrium, where no player can improve their '
        'H-score by switching their strategy.',
    'settled':
        'The equilibrium generally has more diverse strategies, because under strategic competition, finding a unique lane is valuable. '
        'This is probably better for drafting in most cases.',
}
