"""What the self-play animation says out loud.

This is the only file to edit for narration. Each key is one beat of the scene, and that beat's
animation plays INSIDE its line: rewriting a line retimes its own beat rather than
desynchronising everything after it. A beat whose line is short waits for the animation, and one
whose line is long holds the last frame until the sentence finishes.

The voice is gTTS, so what is written here is what is spoken -- spell out anything a reader would
say differently from how it is written ('sigma', 'twenty-six').
"""

NARRATION = {
    'opening':
        'These are expected category-level win rates for the top players, at first generated by the algorithm assuming that '
        'opposing teams will be entirely balanced; certain punting profiles consistently seem optimal in this context.',
    'early_passes':
        'The self-play process has teams re-calibrate themselves against the rest of the field repeatedly, finding new strategies '
        'based on the current field.  Every pass re-solves half of the players at a time. The fictitious managers see how popular '
        'certain punts are, and adjust their strategies to try to find more unique lanes that will work better.', 
    're_estimation':
        'The players are sorted in overall H-score order. The top twelve players and their associated strategy profiles '
        'constitute the drafting context, against which strategies are optimized and evaluated. As overall H-scores change '
        'during the drafting process, players move up and down, and therefore the top twelve changes as well.',
    'late_passes':
        'Over time, the changes get smaller. That means the field is approaching an equilibrium, where no player can improve their '
        'H-score by switching their strategy.',
    'settled':
        'The equilibrium generally has more diverse strategies, because under strategic competition, finding a unique lane is valuable. '
        'This is probably better for drafting in most cases.',
}
