CREATE TABLE IF NOT EXISTS PLAYER_REFERENCE_TABLE (
    MASTER_PLAYER_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    YAHOO_PLAYER_ID int NOT NULL FOREIGN KEY REFERENCES YAHOO_PLAYER_TABLE(YAHOO_PLAYER_ID)
    NBA_PLAYER_ID int NOT NULL FOREIGN KEY REFERENCES NBA_PLAYER_TABLE(NBA_PLAYER_ID)
    DARKO_PLAYER_ID int NOT NULL FOREIGN KEY REFERENCES DARKO_PLAYER_TABLE(SEASON_ID)
);


CREATE TABLE IF NOT EXISTS YAHOO_PLAYER_TABLE (
    YAHOO_PLAYER_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,YAHOO_PLAYER_NAME str NOT NULL
    ,PG_ELIGIBLE boolean NOT NULL
    ,SG_ELIGIBLE boolean NOT NULL
    ,PF_ELIGIBLE boolean NOT NULL
    ,SF_ELIGIBLE boolean NOT NULL
    ,C_ELIGIBLE boolean NOT NULL
    ,IS_ACTIVE boolean NOT NULL
    ,IS_INJURED boolean NOT NULL
    ,UPDATE_DATE date NOT NULL
);

CREATE TABLE IF NOT EXISTS DARKO_PLAYER_TABLE (
    DARKO_PLAYER_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,DARKO_PLAYER_NAME str NOT NULL 
    ,FIELD_GOAL_ATTEMPTS int NOT NULL 
    ,FIELD_GOALS_MADE int NOT NULL 
    ,FREE_THROW_ATTEMPTS int NOT NULL 
    ,FREE_THROWS_MADE int NOT NULL 
    ,THREES int NOT NULL 
    ,POINTS int NOT NULL 
    ,REBOUNDS int NOT NULL 
    ,ASSISTS int NOT NULL 
    ,STEALS int NOT NULL 
    ,BLOCKS int NOT NULL 
    ,TURNOVERS int NOT NULL 
    ,MINUTES_PLAYED Decimal(6,2) NOT NULL 
    ,UPDATE_DATE date NOT NULL
);

CREATE TABLE IF NOT EXISTS NBA_PLAYER_TABLE (
    NBA_PLAYER_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,NBA_PLAYER_NAME str NOT NULL 
    ,UPDATE_DATE date NOT NULL
);

CREATE TABLE IF NOT EXISTS SEASON_TABLE (
    SEASON_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,SEASON str
    ,UPDATE_DATE date NOT NULL
);

CREATE TABLE IF NOT EXISTS TEAM_TABLE (
    TEAM_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,TEAM_NAME str NOT NULL
    ,UPDATE_DATE date NOT NULL
);

CREATE TABLE IF NOT EXISTS GAME_TABLE (
    GAME_ID int NOT NULL PRIMARY KEY AUTO INCREMENT
    ,SEASON_ID int NOT NULL FOREIGN KEY REFERENCES SEASON_TABLE(SEASON_ID)
    ,HOME_TEAM_ID int NOT NULL FOREIGN KEY REFERENCES TEAM_TABLE(TEAM_ID)
    ,AWAY_TEAM_ID int NOT NULL FOREIGN KEY REFERENCES TEAM_TABLE(TEAM_ID)
    ,GAME_DATE date NOT NULL
    ,UPDATE_DATE date NOT NULL

   ....
);

CREATE TABLE IF NOT EXISTS BOX_SCORE_TABLE (
    BOX_SCORE_ID int NOT NULL PRIMARY KEYAUTO INCREMENT
    ,GAME_ID int NOT NULL FOREIGN KEY REFERENCES GAME_TABLE(GAME_ID)
    ,NBA_PLAYER_ID int NOT NULL FOREIGN KEY REFERENCES PLAYER_TABLE(PLAYER_ID)
    ,FIELD_GOAL_ATTEMPTS int NOT NULL 
    ,FIELD_GOALS_MADE int NOT NULL 
    ,FREE_THROW_ATTEMPTS int NOT NULL 
    ,FREE_THROWS_MADE int NOT NULL 
    ,THREES int NOT NULL 
    ,POINTS int NOT NULL 
    ,REBOUNDS int NOT NULL 
    ,ASSISTS int NOT NULL 
    ,STEALS int NOT NULL 
    ,BLOCKS int NOT NULL 
    ,TURNOVERS int NOT NULL 
    ,MINUTES_PLAYED Decimal(6,2) NOT NULL 
    ,UPDATE_DATE date NOT NULL
);
