CREATE OR REPLACE VIEW WEEKLY_NUMBERS_VIEW AS
SELECT A.NBA_PLAYER_ID
, B.NBA_PLAYER_NAME
, C.WEEK
, D.SEASON
, SUM(POINTS) AS POINTS
, SUM(REBOUNDS) AS REBOUNDS
, SUM(ASSISTS) AS ASSISTS
, SUM(STEALS) AS STEALS
, SUM(BLOCKS) AS BLOCKS
, SUM(THREES) AS THREES 
, SUM(TURNOVERS) AS TURNOVERS
, SUM(FREE_THROW_ATTEMPTS) AS FREE_THROW_ATTEMPTS
, SUM(FREE_THROWS_MADE) AS FREE_THROWS_MADE
, SUM(FIELD_GOAL_ATTEMPTS) AS FIELD_GOAL_ATTEMPTS
, SUM(FIELD_GOALS_MADE) AS FIELD_GOALS_MADE
FROM BOX_SCORE_TABLE AS A
JOIN NBA_PLAYER_TABLE AS B ON A.NBA_PLAYER_ID = B.NBA_PLAYER_ID
JOIN (SELECT *, WEEK(GAME_DATE) AS WEEK FROM NBA_GAME_TABLE) AS C 
on A.GAME_ID = C.GAME_ID 
JOIN NBA_SEASON_TABLE D on C.SEASON_ID = D.SEASON_ID
GROUP BY 
A.NBA_PLAYER_ID , B.NBA_PLAYER_NAME , C.WEEK , D.SEASON


CREATE OR REPLACE VIEW WEEKLY_NUMBERS_EXPANDED_VIEW AS 
SELECT A.SEASON, A.NBA_PLAYER_ID, A.NBA_PLAYER_NAME, B.WEEK
, POINTS, REBOUNDS, ASSISTS, STEALS, BLOCKS, THREES, TURNOVERS, FREE_THROW_ATTEMPTS
, FREE_THROWS_MADE, FIELD_GOAL_ATTEMPTS, FIELD_GOALS_MADE FROM
(SELECT DISTINCT SEASON, NBA_PLAYER_ID, NBA_PLAYER_NAME FROM WEEKLY_NUMBERS_VIEW ) A
LEFT JOIN (SELECT DISTINCT SEASON, WEEK FROM WEEKLY_NUMBERS_VIEW) B ON A.SEASON = B.SEASON
LEFT JOIN WEEKLY_NUMBERS C ON A.NBA_PLAYER_ID = C.NBA_PLAYER_ID
                            AND A.SEASON = C.SEASON
                            AND B.WEEK = C.WEEK
ORDER BY SEASON, NBA_PLAYER_NAME

CREATE OR REPLACE VIEW YAHOO_POSITIONS_VIEW AS 
SELECT D.SEASON, B.NBA_PLAYER_ID, C.NBA_PLAYER_NAME, A.ELIGIBLE, A.POSITION
FROM YAHOO_PLAYER_POSITION_ELIGIBILITY_TABLE A
JOIN PLAYER_REFERENCE_TABLE B On A.YAHOO_PLAYER_ID = B.YAHOO_PLAYER_ID
JOIN NBA_PLAYER_TABLE C ON B.NBA_PLAYER_ID = C.NBA_PLAYER_ID
JOIN NBA_SEASON_TABLE D on A.SEASON_ID = D.SEASON_ID
WHERE A.POSITION NOT IN ('Util','F','G')
ORDER BY SEASON, NBA_PLAYER_NAME

CREATE OR REPLACE VIEW AVERAGE_NUMBERS_VIEW AS
SELECT A.NBA_PLAYER_ID
, B.NBA_PLAYER_NAME
, D.SEASON
, AVG(POINTS) AS POINTS
, AVG(REBOUNDS) AS REBOUNDS
, AVG(ASSISTS) AS ASSISTS
, AVG(STEALS) AS STEALS
, AVG(BLOCKS) AS BLOCKS
, AVG(THREES) AS THREES 
, AVG(TURNOVERS) AS TURNOVERS
, AVG(FREE_THROW_ATTEMPTS) AS FREE_THROW_ATTEMPTS
, AVG(FREE_THROWS_MADE) AS FREE_THROWS_MADE
, AVG(FIELD_GOAL_ATTEMPTS) AS FIELD_GOAL_ATTEMPTS
, AVG(FIELD_GOALS_MADE) AS FIELD_GOALS_MADE
, COUNT(POINTS)/82 AS GAMES_PLAYED_PERCENT //this needs to be fixed eventually
, F.POSITION_LIST
FROM BOX_SCORE_TABLE AS A
JOIN NBA_PLAYER_TABLE AS B ON A.NBA_PLAYER_ID = B.NBA_PLAYER_ID
JOIN (SELECT *, WEEK(GAME_DATE) AS WEEK FROM NBA_GAME_TABLE) AS C 
ON A.GAME_ID = C.GAME_ID 
JOIN NBA_SEASON_TABLE D on C.SEASON_ID = D.SEASON_ID
JOIN PLAYER_REFERENCE_TABLE E ON A.NBA_PLAYER_ID = E.NBA_PLAYER_ID
LEFT JOIN (SELECT YAHOO_PLAYER_ID, SEASON_ID, LISTAGG(POSITION, ',') AS POSITION_LIST 
            FROM YAHOO_PLAYER_POSITION_ELIGIBILITY_TABLE
            WHERE ELIGIBLE = TRUE
            AND POSITION NOT IN ('Util','F','G')
            GROUP BY YAHOO_PLAYER_ID, SEASON_ID) F 
ON D.SEASON_ID = F.SEASON_ID
AND E.YAHOO_PLAYER_ID = F.YAHOO_PLAYER_ID
GROUP BY 
A.NBA_PLAYER_ID,B.NBA_PLAYER_NAME,D.SEASON, F.POSITION_LIST //guaranteed to be unique for a player name/season

CREATE OR REPLACE VIEW DARKO_VIEW AS
SELECT A.NBA_PLAYER_ID, NBA_PLAYER_NAME
, FIELD_GOAL_ATTEMPTS, FIELD_GOAL_PERCENT, FREE_THROW_ATTEMPTS, FREE_THROW_PERCENT
, THREES, POINTS, REBOUNDS, ASSISTS, STEALS, BLOCKS, TURNOVERS, POSITION_LIST
FROM DARKO_PLAYER_TABLE A
JOIN PLAYER_REFERENCE_TABLE B ON A.NBA_PLAYER_ID = B.NBA_PLAYER_ID
JOIN NBA_PLAYER_TABLE C ON A.NBA_PLAYER_ID = C.NBA_PLAYER_ID
LEFT JOIN (SELECT YAHOO_PLAYER_ID, SEASON_ID, LISTAGG(POSITION, ',') AS POSITION_LIST 
            FROM YAHOO_PLAYER_POSITION_ELIGIBILITY_TABLE 
            WHERE ELIGIBLE = TRUE
            AND POSITION NOT IN ('Util','F','G')
            GROUP BY YAHOO_PLAYER_ID, SEASON_ID) D
ON B.YAHOO_PLAYER_ID = D.YAHOO_PLAYER_ID
WHERE D.SEASON_ID = (SELECT MAX(SEASON_ID) FROM NBA_SEASON_TABLE)
AND A.UPDATE_TIMESTAMP = (SELECT MAX(UPDATE_TIMESTAMP) FROM DARKO_PLAYER_TABLE)
