// default_season_rosters.ts
// Pre-computed default Season Mode rosters: EC scoring, 2024-25 historical data,
// 12 drafters, 13 picks, snake-drafted by H-score rank (empty board).
// Used to pre-fill the Season Mode roster table consistently across the app and tests.

export const DEFAULT_SEASON_ROSTERS: Record<string, string[]> = {
    'Drafter 1': [
        'Shai Gilgeous-Alexander (PG,SG)',
        'Brook Lopez (C)',
        'Bam Adebayo (C,PF)',
        'Rudy Gobert (C)',
        'Michael Porter Jr. (SF,PF)',
        'Isaiah Hartenstein (C)',
        'Miles Bridges (SF,PF)',
        'Daniel Gafford (C,PF)',
        'Andrew Nembhard (PG,SG)',
        'Buddy Hield (SG,SF)',
        'Mike Conley (PG)',
        'Gary Trent Jr. (PG,SG,SF)',
        'Justin Champagnie (SG,SF)',
    ],
    'Drafter 2': [
        'Nikola Jokic (C)',
        'Pascal Siakam (C,SF,PF)',
        'DeMar DeRozan (SF,PF)',
        'Onyeka Okongwu (C,PF)',
        'Scottie Barnes (PG,SG,SF,PF)',
        'Tyrese Maxey (PG,SG)',
        'Russell Westbrook (PG,SG)',
        'Yves Missi (C)',
        'Malik Monk (PG,SG,SF)',
        'Ty Jerome (PG,SG)',
        'Derrick Jones Jr. (SF,PF)',
        'Kyshawn George (SG,SF)',
        'Andrew Wiggins (SF,PF)',
    ],
    'Drafter 3': [
        'Tyrese Haliburton (PG,SG)',
        'Derrick White (PG,SG)',
        'Jalen Williams (C,SG,SF,PF)',
        'Jamal Murray (PG,SG)',
        "De'Aaron Fox (PG,SG)",
        'Jalen Green (PG,SG)',
        'Cason Wallace (PG,SG)',
        'Naji Marshall (SG,SF,PF)',
        'Norman Powell (SG,SF)',
        'Ja Morant (PG)',
        'RJ Barrett (SG,SF,PF)',
        'Haywood Highsmith (SF,PF)',
        'Paolo Banchero (SF,PF)',
    ],
    'Drafter 4': [
        'Karl-Anthony Towns (C,PF)',
        'Devin Booker (PG,SG)',
        'Chris Paul (PG)',
        'Jalen Duren (C)',
        'Coby White (PG,SG)',
        'Kyrie Irving (PG,SG)',
        'Scotty Pippen Jr. (PG,SG)',
        'Goga Bitadze (C)',
        'P.J. Washington (SF,PF)',
        'Santi Aldama (C,PF)',
        'Brandin Podziemski (PG,SG)',
        "Kel'el Ware (C,PF)",
        'LaMelo Ball (PG,SG)',
    ],
    'Drafter 5': [
        'James Harden (PG,SG)',
        'Cade Cunningham (PG,SG)',
        'Jaren Jackson Jr. (C,PF)',
        'Anthony Davis (C,PF)',
        'Zach LaVine (SG,SF)',
        'Jakob Poeltl (C)',
        'Trey Murphy III (SG,SF,PF)',
        'Kelly Oubre Jr. (SG,SF)',
        'Isaiah Stewart (C,PF)',
        'Keldon Johnson (SG,SF,PF)',
        'Peyton Watson (SF,PF)',
        'Taurean Prince (SG,SF)',
        'Donte DiVincenzo (PG,SG,SF)',
    ],
    'Drafter 6': [
        'Giannis Antetokounmpo (C,PF)',
        'Jarrett Allen (C)',
        'Kevin Durant (SF,PF)',
        'Alperen Sengun (C)',
        'Franz Wagner (SF,PF)',
        'Jalen Brunson (PG)',
        'Jaylen Brown (SG,SF)',
        'Draymond Green (C,PF)',
        'Harrison Barnes (SF,PF)',
        'Dillon Brooks (SG,SF,PF)',
        'Bilal Coulibaly (SG,SF)',
        'Caris LeVert (SG,SF)',
        'Al Horford (C,PF)',
    ],
    'Drafter 7': [
        'Josh Hart (SG,SF,PF)',
        'Evan Mobley (C,PF)',
        'Trae Young (PG)',
        'Desmond Bane (SG,SF)',
        'Luka Doncic (PG,SG)',
        'Deni Avdija (SF,PF)',
        'Tari Eason (SF,PF)',
        'Julius Randle (C,PF)',
        'Quentin Grimes (SG,SF)',
        'Bennedict Mathurin (SG,SF)',
        'Kentavious Caldwell-Pope (SG,SF)',
        'Kristaps Porzingis (C,PF)',
        'Jonathan Isaac (SF,PF)',
    ],
    'Drafter 8': [
        'Jayson Tatum (SF,PF)',
        'Domantas Sabonis (C)',
        'Amen Thompson (PG,SG,SF,PF)',
        'Donovan Mitchell (PG,SG)',
        'Payton Pritchard (PG,SG)',
        'Jimmy Butler (SF,PF)',
        'Nic Claxton (C)',
        'Luguentz Dort (SG,SF)',
        'Spencer Dinwiddie (PG,SG)',
        'Julian Champagnie (SF,PF)',
        'Stephon Castle (PG,SG)',
        'Alex Caruso (SG,SF)',
        'CJ McCollum (PG,SG)',
    ],
    'Drafter 9': [
        'Dyson Daniels (PG,SG,SF)',
        'Nikola Vucevic (C,PF)',
        'Josh Giddey (PG,SG,SF)',
        'Austin Reaves (PG,SG)',
        'Toumani Camara (SG,SF,PF)',
        'Keegan Murray (SF,PF)',
        'Tyus Jones (PG)',
        'Malik Beasley (SG,SF)',
        'Jrue Holiday (PG,SG)',
        'Bub Carrington (PG,SG)',
        'Shaedon Sharpe (SG,SF)',
        'Anthony Black (PG,SG)',
        'Kevin Porter Jr. (PG)',
    ],
    'Drafter 10': [
        'Ivica Zubac (C)',
        'Tyler Herro (PG,SG)',
        'Christian Braun (SG,SF)',
        'Myles Turner (C)',
        'Walker Kessler (C)',
        'Naz Reid (C,PF)',
        'Jonas Valanciunas (C)',
        'Cameron Johnson (SF,PF)',
        'Ausar Thompson (SF,PF)',
        'Klay Thompson (SG,SF)',
        'Fred VanVleet (PG)',
        'Aaron Wiggins (SG,SF)',
        'Bradley Beal (PG,SG,SF)',
    ],
    'Drafter 11': [
        'Stephen Curry (PG,SG)',
        'Victor Wembanyama (C)',
        'O.G. Anunoby (SF,PF)',
        'Damian Lillard (PG)',
        'Tobias Harris (SF,PF)',
        'Keon Ellis (PG,SG,SF)',
        'T.J. McConnell (PG)',
        'Kris Dunn (PG,SG)',
        'Alex Sarr (C,PF)',
        "Royce O'Neale (SF,PF)",
        "De'Andre Hunter (SF,PF)",
        'Davion Mitchell (PG,SG)',
        'Isaiah Joe (PG,SG)',
    ],
    'Drafter 12': [
        'Anthony Edwards (SG,SF)',
        'LeBron James (SF,PF)',
        'Jaden McDaniels (SF,PF)',
        'Darius Garland (PG)',
        'Jordan Poole (PG,SG)',
        'Mikal Bridges (SG,SF,PF)',
        'Devin Vassell (SG,SF)',
        'Anfernee Simons (PG,SG)',
        'Dennis Schroder (PG,SG)',
        'Jalen Johnson (SF,PF)',
        'Zach Edey (C)',
        'Obi Toppin (PF)',
        'Collin Sexton (PG,SG)',
    ],
}
