// default_season_rosters.ts
// Pre-computed default Season Mode rosters: EC scoring, 2025-26 historical data,
// 12 drafters, 13 picks, snake-drafted by H-score rank.
// Used to pre-fill the Season Mode roster table consistently across the app and tests.

export const DEFAULT_SEASON_ROSTERS: Record<string, string[]> = {
    'Drafter 1': [
        'Nikola Jokic (C)',
        'Bam Adebayo (C,PF)',
        'James Harden (PG,SG)',
        'O.G. Anunoby (PF,SF)',
        'Collin Gillespie (PG,SG)',
        'Keldon Johnson (PF,SF)',
        'Ayo Dosunmu (PG,SG,SF)',
        'Maxime Raynaud (C)',
        'Naji Marshall (PF,SG,SF)',
        'Jordan Goodwin (PG,SG,SF)',
        'Sam Hauser (PF,SF)',
        'Kevin Porter Jr. (PG,SG)',
        'Dylan Harper (PG,SG)',
    ],
    'Drafter 2': [
        'Shai Gilgeous-Alexander (PG)',
        'Cooper Flagg (PG,SG,SF)',
        'Donovan Clingan (C)',
        'Brandon Ingram (PF,SG,SF)',
        'Jaylen Brown (SG,SF)',
        'Tre Jones (PG,SG)',
        'Cason Wallace (PG,SG,SF)',
        'Jaime Jaquez Jr. (PF,SG,SF)',
        'Jalen Suggs (PG,SG)',
        'Justin Champagnie (PF,SF)',
        'Alex Sarr (C)',
        'Jimmy Butler (PF,SG,SF)',
        'Ivica Zubac (C)',
    ],
    'Drafter 3': [
        'Victor Wembanyama (C,PF)',
        'Kon Knueppel (SG,SF)',
        'Anthony Edwards (PG,SG)',
        'Julian Champagnie (SG,SF)',
        'Jabari Smith Jr. (C,PF,SF)',
        'Deandre Ayton (C)',
        'CJ McCollum (PG,SG)',
        'John Collins (C,PF)',
        'Tim Hardaway Jr. (SG,SF)',
        'Jaren Jackson Jr. (C,PF)',
        'Ace Bailey (PF,SG,SF)',
        'AJ Green (PG,SG,SF)',
        'Isaiah Stewart (C,PF)',
    ],
    'Drafter 4': [
        'Tyrese Maxey (PG)',
        'Derrick White (PG,SG)',
        'Onyeka Okongwu (C,PF)',
        'Jay Huff (C)',
        'Immanuel Quickley (PG,SG)',
        'Deni Avdija (PF,SG,SF)',
        'Myles Turner (C)',
        'Devin Vassell (SG,SF)',
        'Quentin Grimes (SG,SF)',
        'Tristan da Silva (PF,SF)',
        'Brook Lopez (C)',
        'Andrew Nembhard (PG,SG)',
        'Grayson Allen (PG,SG,SF)',
    ],
    'Drafter 5': [
        'Scottie Barnes (C,PF,SG,SF)',
        'Dyson Daniels (PG,SG,SF)',
        'Alperen Sengun (C,PF)',
        'Ausar Thompson (PF,SG,SF)',
        "De'Aaron Fox (PG,SG)",
        'LeBron James (PF,SF)',
        'Moussa Diabate (C)',
        'Zion Williamson (C,PF,SF)',
        'Stephon Castle (PG,SG)',
        'Precious Achiuwa (C,PF)',
        'Mitchell Robinson (C)',
        'Jock Landale (C)',
        'P.J. Washington (C,PF,SF)',
    ],
    'Drafter 6': [
        'Jamal Murray (PG,SG)',
        'Trey Murphy III (PF,SG,SF)',
        'Jalen Duren (C)',
        'Ryan Rollins (PG,SG)',
        'Wendell Carter Jr. (C)',
        'Devin Booker (PG,SG)',
        'Josh Hart (PF,SG,SF)',
        'Duncan Robinson (SG,SF)',
        'Mark Williams (C)',
        'Jake LaRavia (PF,SF)',
        'Davion Mitchell (PG)',
        'Ajay Mitchell (PG,SG)',
        'Bruce Brown (PG,SG)',
    ],
    'Drafter 7': [
        'Kawhi Leonard (PF,SF)',
        'Chet Holmgren (C,PF)',
        "Kel'el Ware (C,PF)",
        'Matas Buzelis (PF,SF)',
        'Donte DiVincenzo (PG,SG)',
        'Brandon Miller (PF,SF)',
        'Sandro Mamukelashvili (C,PF)',
        'Austin Reaves (PG,SG,SF)',
        'Norman Powell (SG,SF)',
        'Jaylon Tyson (SG,SF)',
        'Javonte Green (SG,SF)',
        'Brice Sensabaugh (PF,SG,SF)',
        'Moses Moody (PF,SG,SF)',
    ],
    'Drafter 8': [
        'Luka Doncic (PG,SG)',
        'Mikal Bridges (PF,SG,SF)',
        'Rudy Gobert (C)',
        'Evan Mobley (C,PF)',
        'Naz Reid (C,PF)',
        'Toumani Camara (C,PF,SF)',
        'Pascal Siakam (C,PF,SF)',
        'Nic Claxton (C)',
        'Jarrett Allen (C)',
        'Anthony Black (PG,SG,SF)',
        'Oso Ighodaro (C)',
        'RJ Barrett (PF,SG,SF)',
        'Giannis Antetokounmpo (C,PF)',
    ],
    'Drafter 9': [
        'Kevin Durant (PF,SG,SF)',
        'Nickeil Alexander-Walker (PG,SG,SF)',
        'Neemias Queta (C,PF)',
        'Reed Sheppard (PG,SG)',
        'Andrew Wiggins (PF,SG,SF)',
        'Miles Bridges (PF,SF)',
        'Michael Porter Jr. (PF,SF)',
        'Lauri Markkanen (PF,SF)',
        'Ryan Kalkbrenner (C)',
        'Max Christie (SG,SF)',
        'Isaiah Joe (SG,SF)',
        'Joel Embiid (C)',
        'Kevin Huerter (SG,SF)',
    ],
    'Drafter 10': [
        'Karl-Anthony Towns (C,PF)',
        'Desmond Bane (SG,SF)',
        'Jalen Brunson (PG)',
        'LaMelo Ball (PG,SG)',
        'Saddiq Bey (PF,SF)',
        'Paolo Banchero (C,PF)',
        "Royce O'Neale (PF,SF)",
        'Keyonte George (PG,SG)',
        'Josh Giddey (PG,SG)',
        'Jeremiah Fears (PG,SG)',
        'Collin Sexton (PG,SG)',
        'Russell Westbrook (PG,SG)',
        'Jarace Walker (PF,SF)',
    ],
    'Drafter 11': [
        'Amen Thompson (PG,SG,SF)',
        'Cade Cunningham (PG,SG)',
        'DeMar DeRozan (PF,SF)',
        'VJ Edgecombe (PG,SG)',
        'Jaden McDaniels (PF,SF)',
        'Derik Queen (C,PF)',
        'Kris Dunn (PG,SG)',
        'Kyle Filipowski (C,PF)',
        'Luke Kornet (C)',
        'Robert Williams III (C)',
        'Dominick Barlow (C,PF)',
        'Daniel Gafford (C)',
        'Goga Bitadze (C)',
    ],
    'Drafter 12': [
        'Donovan Mitchell (PG,SG)',
        'Jalen Johnson (PF,SF)',
        'Payton Pritchard (PG)',
        'Julius Randle (C,PF)',
        'Nikola Vucevic (C)',
        'Brandin Podziemski (PG,SG)',
        'Cam Spencer (PG,SG)',
        'Stephen Curry (PG)',
        'Bobby Portis (C,PF)',
        'Tobias Harris (PF)',
        'Luke Kennard (PG,SG)',
        'Cedric Coward (SG,SF)',
        'Jrue Holiday (PG,SG)',
    ],
}
